name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
    - name: Install Composer packages
      uses: ramsey/composer-install@v3
    - name: Run Migrations
      run: |
        php artisan migrate --force
    - name: Seed Database
      run: |
        php artisan db:seed --force
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: |
          application
          vendor
          public