name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_DEV: 1
      DB_USERNAME: root
      DB_PASSWORD: 
      DB_NAME: suitableOpdracht
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
    - name: Install Composer packages
      uses: ramsey/composer-install@v3
    - name: Run Migrations
      run: |
        mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} < path/to/migration.sql
    - name: Seed Database
      run: |
        mysql -u ${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }} < path/to/seeder.sql
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: |
          application
          vendor
          public